### ISSUE TITLE
Avoid that mediasoup-worker-prebuild CI task runs for every PR

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1243]
I'm tired of seeing **so many** `mediasoup-worker-prebuild` CI actions running (and failing) despite the task is supposed to only run after a release. All those tasks fail due to "GitHub Releases requires a tag". Problem is that, before failing, they completely build mediasoup, which means lot of useless and wasted time:

<img width="526" alt="CleanShot-2023-11-25-at-12 04 34@2x" src="https://github.com/versatica/mediasoup/assets/16191/87eff6c5-6f11-4683-a4eb-60ef250bddf0">

In theory, the `mediasoup-worker-prebuild` task should only run after releases, but obviously it's not working as expected (or perhaps the configuration of the task is wrong, no idea):

`mediasoup-worker-prebuild.yaml`

```yaml
name: mediasoup-worker-prebuild

on:
  push:
    # Only trigger for production releases.
    tags:
      - "*.*.*"

  # Only trigger when other workflows succeeded.
  workflow_run:
    workflows: [mediasoup-worker, mediasoup-node, mediasoup-rust]
    types:
      - completed

jobs:
  # [etc]  
```

**Comment by ibc** [comment]
Some info: 
- https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
- https://github.com/softprops/action-gh-release

**Comment by ibc** [comment]
Maybe this works: https://github.com/versatica/mediasoup/pull/1280

**Comment by ibc** [comment]
Let's move the discussion here.

So I'm working in a mediasoup fork under my `ibc` account (https://github.com/ibc/mediasoup) and applied the changes in `mediasoup-worker-prebuild.yaml` that are supposed to make it ONLY run after a release:

```yaml
name: mediasoup-worker-prebuild

# Only trigger for production releases.
on:
  push:
    release:
      types:
        - published

  # Only trigger when other workflows succeeded.
  workflow_run:
    workflows: [mediasoup-worker, mediasoup-node, mediasoup-rust]
    types:
      - completed
```

But then I've pushed a random commit to `v3` branch and there we have the `mediasoup-worker-prebuild`  job running again:

![CleanShot-2023-12-29-at-10 57 34@2x](https://github.com/versatica/mediasoup/assets/16191/e742ed51-6128-44ca-9910-2b65f51bf679)

:(

**Comment by nazar-pc** [comment]
Did you merge those changes into `v3` (or whatever the default branch in your fork is) yet? Because there are some triggers that are defined by the default branch.

**Comment by ibc** [comment]
> Did you merge those changes into `v3` (or whatever the default branch in your fork is) yet? Because there are some triggers that are defined by the default branch.

I pushed directly to v3 (default) branch, yes. So then what? Of course we are supposed to only run this job in default branch (when a release happens).

**Comment by nazar-pc** [comment]
Are you sure this is a valid syntax?:
```yaml
on:
  push:
    release:
      types:
        - published
```

I do not see `release` in documentation, so I suspect it might be triggered on every push.

**Comment by ibc** [comment]
I'll check that. 

BTW the job is run even in PRs: https://github.com/ibc/mediasoup/pull/1

**Comment by nazar-pc** [comment]
Looks like it should be this:
```yaml
on:
  release:
    types: [published]
```
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release

It is a separate trigger, not part of the push
