### ISSUE TITLE
Include ubuntu-24.04 in CI

### ISSUE THREAD

**Issue by ibc** [versatica/mediasoup#1441]
`ubuntu-24.04` is already available: https://github.com/actions/runner-images/issues/9848

Let's add it in all our CI actions.

**Comment by ibc** [comment]
Ironically we were already using ubuntu-24.04 in `mediasoup-node.yaml` but not in others. I've added them in this unrelated PR https://github.com/versatica/mediasoup/pull/1440 in commit https://github.com/versatica/mediasoup/pull/1440/commits/600ff0467f768ecbc6e6beb4546001ea3c64ff85.

But amazingly it fails...

https://github.com/versatica/mediasoup/actions/runs/10319604062/job/28568334351?pr=1440

Ok, we must do same as we do for macos versions:

```yaml
      # We need to install pip invoke manually.
      - if: runner.os != 'macOS'
        name: pip3 install invoke
        run: pip3 install invoke

      # In macOS we need to specify this option.
      - if: runner.os == 'macOS'
        name: pip3 install --break-system-packages invoke
        run: pip3 install --break-system-packages invoke
```
